# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\x1f\n\rSquareRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\" \n\x0eSquareResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32O\n\nCalculator\x12\x41\n\x06Square\x12\x19.calculator.SquareRequest\x1a\x1a.calculator.SquareResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SQUAREREQUEST']._serialized_start=32
  _globals['_SQUAREREQUEST']._serialized_end=63
  _globals['_SQUARERESPONSE']._serialized_start=65
  _globals['_SQUARERESPONSE']._serialized_end=97
  _globals['_CALCULATOR']._serialized_start=99
  _globals['_CALCULATOR']._serialized_end=178
# @@protoc_insertion_point(module_scope)
